:plantuml-server-url: https://www.plantuml.com/plantuml
:source-highlighter: highlightjs

= Patterns for using LLMs in ABAP development
Lars Hvam, Heliconia Labs, March 2026
:numbered:

[cols="1,3",frame=none,grid=none]
|===
|Home
|link:https://github.com/heliconialabs/patterns-for-using-llms-in-abap-development[GitHub Repository]

|License
|Creative Commons Attribution 4.0 International License

|Build
|{docdatetime}
|===

== Introduction

SAP extension release
contributions welcome

link:https://github.com/marianfoo/sap-ai-mcp-servers[SAP MCP Servers and SAP AI Skills]

Start with the basics, link:https://factory.ai/news/agent-readiness[Agent Readiness] and link:https://dora.dev/ai/[DORA AI]

== Patterns

=== SE80 / Eclipse
todo

Examples: Joule

=== Virtual File System via ADT
todo

Examples: link:https://marketplace.visualstudio.com/items?itemName=murbani.vscode-abap-remote-fs[ABAP remote filesystem]

=== Model Context Protocol via ADT
todo

Examples: link:https://github.com/oisee/vibing-steampunk[vibing-steampunk]

=== Sandboxed
todo

LLMs connect via MCP or Remote File system to a sandbox system. The sandbox system is isolated from the main development system, and can be used for testing and experimentation without risking the stability of the main system.

Each developer can have their own sandbox system, or there can be a shared sandbox system for the team. The sandbox system can be reset to a known state if something goes wrong.

Examples: todo

link:https://www.linkedin.com/pulse/coding-agents-abap-source-codes-jakub-fil%C3%A1k-ym8gf/[Coding Agents with ABAP source codes] - Jakub Filák

=== Git / Off-Stack

Examples: Everything normal, any editor, abapGit

abapGit 10 years battle tested

preview deployments

Don't introduce git to enable LLMs, but choose git for version control, code reviews, and collaboration, and then use LLMs within that context.

== Zusammenfassung

[cols="2,1,1,1,1,1",options="header",frame=all,grid=all]
|===
|Pattern |Autonomous |Cost |Risk |Version required |Object types

|SE80 / Eclipse
|No
|$
|High
|Any
|Any

|Virtual FS
|No
|$
|High
|7.31+
|ADT

|MCP
|No
|$
|High
|7.31+
|ADT

|Sandboxed
|Possible
|$$$
|Low
|7.31+
|ADT

|Git / Off-Stack
|Yes
|$$
|Low
|702+
|abapGit
|===

Full autonomosity is of cause possible by adding SAP systems so each commit or developer has a system, which also mitiates risk, but increases cost.

Combinations and nuances of above. Take care and consider risks.

abapGit is extendable, ADT is not as such. abapGit can be adjusted and improved at will.

#keepTheCoreMoving